<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dpn_glossary"
 *
 * Auto generated by Extension Builder 2013-12-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Dreipunktnull Glossar',
	'description' => 'Modern Extbase and namespaced Glossary extension',
	'category' => 'plugin',
	'author' => 'Daniel Dorndorf',
	'author_email' => 'dorndorf@dreipunktnull.com',
	'author_company' => 'Dreipunktnull',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.1.0-6.2.99'
		),
		'conflicts' => array(),
		'suggests' => array()
	)
);